name: blog_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0' # Ensure the correct SDK range

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image1.png
    - assets/image2.webp
    - assets/image3.webp
    - assets/image4.webp
    - assets/image5.webp
    - assets/image6.webp
    - assets/image7.webp
    - assets/image8.webp
    - assets/image9.webp
    - assets/image10.jpg
