// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4iWI3OPPzw-7ZLao4i33Ph54x01XhiUw',
    appId: '1:811363738463:web:0f12a5231f7b9355220cea',
    messagingSenderId: '811363738463',
    projectId: 'blog-app-2-34fe0',
    authDomain: 'blog-app-2-34fe0.firebaseapp.com',
    databaseURL: 'https://blog-app-2-34fe0-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-2-34fe0.firebasestorage.app',
    measurementId: 'G-EHVRPTMTNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZUfo6A8zD3opRrjBiIFKF7wDxcXxqQY',
    appId: '1:811363738463:android:757e84373df9e61c220cea',
    messagingSenderId: '811363738463',
    projectId: 'blog-app-2-34fe0',
    databaseURL: 'https://blog-app-2-34fe0-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-2-34fe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvSUlQoZtccFfxQAVF21OdEGvZoUItqc',
    appId: '1:811363738463:ios:006522cb4a5c3e57220cea',
    messagingSenderId: '811363738463',
    projectId: 'blog-app-2-34fe0',
    databaseURL: 'https://blog-app-2-34fe0-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-2-34fe0.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCvSUlQoZtccFfxQAVF21OdEGvZoUItqc',
    appId: '1:811363738463:ios:006522cb4a5c3e57220cea',
    messagingSenderId: '811363738463',
    projectId: 'blog-app-2-34fe0',
    databaseURL: 'https://blog-app-2-34fe0-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-2-34fe0.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4iWI3OPPzw-7ZLao4i33Ph54x01XhiUw',
    appId: '1:811363738463:web:94159a3244083661220cea',
    messagingSenderId: '811363738463',
    projectId: 'blog-app-2-34fe0',
    authDomain: 'blog-app-2-34fe0.firebaseapp.com',
    databaseURL: 'https://blog-app-2-34fe0-default-rtdb.firebaseio.com',
    storageBucket: 'blog-app-2-34fe0.firebasestorage.app',
    measurementId: 'G-T70DFNKKFX',
  );

}