// dummy_data.dart

import '../models/blog_model.dart';

final List<Blog> dummyBlogs = [
  Blog(
    id: '1',
    title: 'learnings from my GATE journey',
    description: 'Learn the basics of Flutter in this comprehensive guide.',
    author: 'Author Sushant',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '2',
    title: 'sources to read for system subjects',
    description: 'Explore different state management techniques in Flutter.',
    author: 'Author Varun',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '3',
    title: 'practice is the key',
    description: 'A step-by-step guide on creating REST APIs with Node.js.',
    author: 'Author siddharth',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '4',
    title: 'consistency is what most difficult to maintain',
    description: 'Improve your Dart skills with these useful tips.',
    author: 'Author Vaibhav',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '5',
    title: 'fear of computer networks subject',
    description: 'Learn about Futures, Streams, and async/await in Dart.',
    author: 'Author akshat',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '6',
    title: 'sources for practice material',
    description: 'A complete guide to building a blog application with Flutter.',
    author: 'Author harsh',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '7',
    title: 'how to manage college and gate',
    description: 'Implement user authentication in your Flutter apps using Firebase.',
    author: 'Author vihan',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '8',
    title: 'Placements vs GATE',
    description: "Enhance your UI skills with Flutter's design principles.",
    author: 'Author aryan',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '9',
    title: 'Life after GATE',
    description: 'Step-by-step guide to deploying a Flutter app to the Play Store and App Store.',
    author: 'Author UMED',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
  Blog(
    id: '10',
    title: 'placement report in IIT/IISC for MTECH',
    description: 'Master animations in Flutter with custom transitions and effects.',
    author: 'Author atif',
    category: 'Education',
    publishDate: DateTime.now(),
    likes: [],
    comments: [],
  ),
];
